# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xjl/GIT/CSTL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xjl/GIT/CSTL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xjl/GIT/CSTL/CMakeFiles /home/xjl/GIT/CSTL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xjl/GIT/CSTL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CSTL

# Build rule for target.
CSTL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CSTL
.PHONY : CSTL

# fast build rule for target.
CSTL/fast:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/build
.PHONY : CSTL/fast

src/algorithm.o: src/algorithm.cpp.o

.PHONY : src/algorithm.o

# target to build an object file
src/algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/algorithm.cpp.o
.PHONY : src/algorithm.cpp.o

src/algorithm.i: src/algorithm.cpp.i

.PHONY : src/algorithm.i

# target to preprocess a source file
src/algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/algorithm.cpp.i
.PHONY : src/algorithm.cpp.i

src/algorithm.s: src/algorithm.cpp.s

.PHONY : src/algorithm.s

# target to generate assembly for a file
src/algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/algorithm.cpp.s
.PHONY : src/algorithm.cpp.s

src/chrono.o: src/chrono.cpp.o

.PHONY : src/chrono.o

# target to build an object file
src/chrono.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/chrono.cpp.o
.PHONY : src/chrono.cpp.o

src/chrono.i: src/chrono.cpp.i

.PHONY : src/chrono.i

# target to preprocess a source file
src/chrono.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/chrono.cpp.i
.PHONY : src/chrono.cpp.i

src/chrono.s: src/chrono.cpp.s

.PHONY : src/chrono.s

# target to generate assembly for a file
src/chrono.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/chrono.cpp.s
.PHONY : src/chrono.cpp.s

src/concurrency.o: src/concurrency.cpp.o

.PHONY : src/concurrency.o

# target to build an object file
src/concurrency.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/concurrency.cpp.o
.PHONY : src/concurrency.cpp.o

src/concurrency.i: src/concurrency.cpp.i

.PHONY : src/concurrency.i

# target to preprocess a source file
src/concurrency.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/concurrency.cpp.i
.PHONY : src/concurrency.cpp.i

src/concurrency.s: src/concurrency.cpp.s

.PHONY : src/concurrency.s

# target to generate assembly for a file
src/concurrency.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/concurrency.cpp.s
.PHONY : src/concurrency.cpp.s

src/container.o: src/container.cpp.o

.PHONY : src/container.o

# target to build an object file
src/container.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/container.cpp.o
.PHONY : src/container.cpp.o

src/container.i: src/container.cpp.i

.PHONY : src/container.i

# target to preprocess a source file
src/container.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/container.cpp.i
.PHONY : src/container.cpp.i

src/container.s: src/container.cpp.s

.PHONY : src/container.s

# target to generate assembly for a file
src/container.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/container.cpp.s
.PHONY : src/container.cpp.s

src/function_object.o: src/function_object.cpp.o

.PHONY : src/function_object.o

# target to build an object file
src/function_object.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/function_object.cpp.o
.PHONY : src/function_object.cpp.o

src/function_object.i: src/function_object.cpp.i

.PHONY : src/function_object.i

# target to preprocess a source file
src/function_object.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/function_object.cpp.i
.PHONY : src/function_object.cpp.i

src/function_object.s: src/function_object.cpp.s

.PHONY : src/function_object.s

# target to generate assembly for a file
src/function_object.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/function_object.cpp.s
.PHONY : src/function_object.cpp.s

src/functional_algorithm_parameter.o: src/functional_algorithm_parameter.cpp.o

.PHONY : src/functional_algorithm_parameter.o

# target to build an object file
src/functional_algorithm_parameter.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/functional_algorithm_parameter.cpp.o
.PHONY : src/functional_algorithm_parameter.cpp.o

src/functional_algorithm_parameter.i: src/functional_algorithm_parameter.cpp.i

.PHONY : src/functional_algorithm_parameter.i

# target to preprocess a source file
src/functional_algorithm_parameter.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/functional_algorithm_parameter.cpp.i
.PHONY : src/functional_algorithm_parameter.cpp.i

src/functional_algorithm_parameter.s: src/functional_algorithm_parameter.cpp.s

.PHONY : src/functional_algorithm_parameter.s

# target to generate assembly for a file
src/functional_algorithm_parameter.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/functional_algorithm_parameter.cpp.s
.PHONY : src/functional_algorithm_parameter.cpp.s

src/internationalization.o: src/internationalization.cpp.o

.PHONY : src/internationalization.o

# target to build an object file
src/internationalization.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/internationalization.cpp.o
.PHONY : src/internationalization.cpp.o

src/internationalization.i: src/internationalization.cpp.i

.PHONY : src/internationalization.i

# target to preprocess a source file
src/internationalization.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/internationalization.cpp.i
.PHONY : src/internationalization.cpp.i

src/internationalization.s: src/internationalization.cpp.s

.PHONY : src/internationalization.s

# target to generate assembly for a file
src/internationalization.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/internationalization.cpp.s
.PHONY : src/internationalization.cpp.s

src/iterator.o: src/iterator.cpp.o

.PHONY : src/iterator.o

# target to build an object file
src/iterator.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/iterator.cpp.o
.PHONY : src/iterator.cpp.o

src/iterator.i: src/iterator.cpp.i

.PHONY : src/iterator.i

# target to preprocess a source file
src/iterator.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/iterator.cpp.i
.PHONY : src/iterator.cpp.i

src/iterator.s: src/iterator.cpp.s

.PHONY : src/iterator.s

# target to generate assembly for a file
src/iterator.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/iterator.cpp.s
.PHONY : src/iterator.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/numeric.o: src/numeric.cpp.o

.PHONY : src/numeric.o

# target to build an object file
src/numeric.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/numeric.cpp.o
.PHONY : src/numeric.cpp.o

src/numeric.i: src/numeric.cpp.i

.PHONY : src/numeric.i

# target to preprocess a source file
src/numeric.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/numeric.cpp.i
.PHONY : src/numeric.cpp.i

src/numeric.s: src/numeric.cpp.s

.PHONY : src/numeric.s

# target to generate assembly for a file
src/numeric.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/numeric.cpp.s
.PHONY : src/numeric.cpp.s

src/numericlimit.o: src/numericlimit.cpp.o

.PHONY : src/numericlimit.o

# target to build an object file
src/numericlimit.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/numericlimit.cpp.o
.PHONY : src/numericlimit.cpp.o

src/numericlimit.i: src/numericlimit.cpp.i

.PHONY : src/numericlimit.i

# target to preprocess a source file
src/numericlimit.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/numericlimit.cpp.i
.PHONY : src/numericlimit.cpp.i

src/numericlimit.s: src/numericlimit.cpp.s

.PHONY : src/numericlimit.s

# target to generate assembly for a file
src/numericlimit.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/numericlimit.cpp.s
.PHONY : src/numericlimit.cpp.s

src/ratio.o: src/ratio.cpp.o

.PHONY : src/ratio.o

# target to build an object file
src/ratio.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/ratio.cpp.o
.PHONY : src/ratio.cpp.o

src/ratio.i: src/ratio.cpp.i

.PHONY : src/ratio.i

# target to preprocess a source file
src/ratio.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/ratio.cpp.i
.PHONY : src/ratio.cpp.i

src/ratio.s: src/ratio.cpp.s

.PHONY : src/ratio.s

# target to generate assembly for a file
src/ratio.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/ratio.cpp.s
.PHONY : src/ratio.cpp.s

src/regular_expression.o: src/regular_expression.cpp.o

.PHONY : src/regular_expression.o

# target to build an object file
src/regular_expression.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/regular_expression.cpp.o
.PHONY : src/regular_expression.cpp.o

src/regular_expression.i: src/regular_expression.cpp.i

.PHONY : src/regular_expression.i

# target to preprocess a source file
src/regular_expression.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/regular_expression.cpp.i
.PHONY : src/regular_expression.cpp.i

src/regular_expression.s: src/regular_expression.cpp.s

.PHONY : src/regular_expression.s

# target to generate assembly for a file
src/regular_expression.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/regular_expression.cpp.s
.PHONY : src/regular_expression.cpp.s

src/stream.o: src/stream.cpp.o

.PHONY : src/stream.o

# target to build an object file
src/stream.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/stream.cpp.o
.PHONY : src/stream.cpp.o

src/stream.i: src/stream.cpp.i

.PHONY : src/stream.i

# target to preprocess a source file
src/stream.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/stream.cpp.i
.PHONY : src/stream.cpp.i

src/stream.s: src/stream.cpp.s

.PHONY : src/stream.s

# target to generate assembly for a file
src/stream.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/stream.cpp.s
.PHONY : src/stream.cpp.s

src/string.o: src/string.cpp.o

.PHONY : src/string.o

# target to build an object file
src/string.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/string.cpp.o
.PHONY : src/string.cpp.o

src/string.i: src/string.cpp.i

.PHONY : src/string.i

# target to preprocess a source file
src/string.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/string.cpp.i
.PHONY : src/string.cpp.i

src/string.s: src/string.cpp.s

.PHONY : src/string.s

# target to generate assembly for a file
src/string.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/string.cpp.s
.PHONY : src/string.cpp.s

src/typetrait.o: src/typetrait.cpp.o

.PHONY : src/typetrait.o

# target to build an object file
src/typetrait.cpp.o:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/typetrait.cpp.o
.PHONY : src/typetrait.cpp.o

src/typetrait.i: src/typetrait.cpp.i

.PHONY : src/typetrait.i

# target to preprocess a source file
src/typetrait.cpp.i:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/typetrait.cpp.i
.PHONY : src/typetrait.cpp.i

src/typetrait.s: src/typetrait.cpp.s

.PHONY : src/typetrait.s

# target to generate assembly for a file
src/typetrait.cpp.s:
	$(MAKE) -f CMakeFiles/CSTL.dir/build.make CMakeFiles/CSTL.dir/src/typetrait.cpp.s
.PHONY : src/typetrait.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CSTL"
	@echo "... src/algorithm.o"
	@echo "... src/algorithm.i"
	@echo "... src/algorithm.s"
	@echo "... src/chrono.o"
	@echo "... src/chrono.i"
	@echo "... src/chrono.s"
	@echo "... src/concurrency.o"
	@echo "... src/concurrency.i"
	@echo "... src/concurrency.s"
	@echo "... src/container.o"
	@echo "... src/container.i"
	@echo "... src/container.s"
	@echo "... src/function_object.o"
	@echo "... src/function_object.i"
	@echo "... src/function_object.s"
	@echo "... src/functional_algorithm_parameter.o"
	@echo "... src/functional_algorithm_parameter.i"
	@echo "... src/functional_algorithm_parameter.s"
	@echo "... src/internationalization.o"
	@echo "... src/internationalization.i"
	@echo "... src/internationalization.s"
	@echo "... src/iterator.o"
	@echo "... src/iterator.i"
	@echo "... src/iterator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/numeric.o"
	@echo "... src/numeric.i"
	@echo "... src/numeric.s"
	@echo "... src/numericlimit.o"
	@echo "... src/numericlimit.i"
	@echo "... src/numericlimit.s"
	@echo "... src/ratio.o"
	@echo "... src/ratio.i"
	@echo "... src/ratio.s"
	@echo "... src/regular_expression.o"
	@echo "... src/regular_expression.i"
	@echo "... src/regular_expression.s"
	@echo "... src/stream.o"
	@echo "... src/stream.i"
	@echo "... src/stream.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
	@echo "... src/typetrait.o"
	@echo "... src/typetrait.i"
	@echo "... src/typetrait.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

